在Java中，异常类都派生`Thorwable`类。
## 自定义异常
异常实际上是一种特殊的类，如果标准异常类无法描述清楚问题，就可以通过派生某个异常类来描述问题。
```java
class XxxxException extends XxxException{
	public ClassNameException(){}
	public ClassNameException(String message){
		super(message)
	}
}
```
#### 异常类型
##### 检查型异常
这类异常必须被try...catch捕获处理，或者在函数签名中声明抛出。例如：`IOException`、`SQLException`
##### 非检查型异常
包括运行时异常`RuntimeException`和错误`Error`。
`RuntimeException`的子类例如：`NullPointerException空指针`，`ArrayIndexOutOfBoundsException下标越界`。
#### 抛出异常
可以在方法的首部指出该方法可能抛出某个异常。
```java
public void func() throws Xxx{}
```
如果方法运行时发生某种错误，被抛出的异常必须被捕获并处理，未被捕获的异常会导致程序错误。

一个方法必须抛出或处理所有可能的检查型异常，未被抛出或处理的检查型异常会导致编译失败。
>如果子类覆盖了父类的方法，子类方法中抛出的检查型异常：不能是父类抛出的异常类型的父类。
>如果父类方法没有抛出检查型异常，子类也不能抛出任何检查型异常
##### 手动抛出异常
```java
throw new XxxException();
```
#### 捕获异常
如果try的语句块中抛出了catch子句中指定的异常，该异常会被捕获并由catch子句进行处理
```java
try{
	...
}catch(ExceptionType e){
	...
}finally{

}
```
如果异常没有被捕获，程序会终止并在控制台打印错误信息，其中包含异常的类型和一个栈轨迹。
>如果try语句与finally子句中都有return语句，在方法返回前会执行finally子句块，finally中新返回的返回值会遮蔽原来的返回值
##### 捕获多个异常
```java
try{
	...
}catch(Xxx e)
{
	...
}catch(...)
...
```
在Java7中，同一个catch子句可以捕获多个异常：
```java
try{
	...
}catch(Xxx | Ccc e){
	...
}
```
>捕获多个异常时，异常变量e是`final`的
##### 再次抛出异常
可以在catch子句中抛出一个异常，通常是在希望改变异常的类型时会这么做。
可以使用`initCause(original)`方法来设置原始异常，再将新的异常抛出。
##### try-with-Resources语句
对于实现了`AutoCloseable`接口的类，Java7为其提供了另一种try...catch...finally来关闭流。
可以指定多个资源
```java
try(Type file = ...)
{
	...
}catch(...){
	...
}
try(Type ...;Type ...){}
```
执行完毕之后会自动调用`file.close()`。
`AutoCloseable`接口有一个`void close() throws Exception`的方法
>AutoCloseable有一个子接口Closeable接口，但该接口抛出的异常为`IOException`

>try-with-Resources语句甚至可以有finally子句和catch，这些子句会在关闭资源后执行
###### 被“抑制”的异常
如果try语句块与close方法都抛出一个异常，在try-with-Resources语句中close抛出的异常会“被抑制”。被抑制的异常会由`addSuppressed()`添加到原来的异常中。
可以使用`getSuppressed`方法来获取那些被抑制的异常
